apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: kargo-advanced
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/victorchu-dp/guestbook
      imageSelectionStrategy: SemVer
      allowTagsRegexes:
      - ^v?[0-9]+\.[0-9]+\.[0-9]+([\+-].*)?$
  - git:
      repoURL: https://github.com/victorchu-dp/kargo-advanced.git
      branch: main
